if exists(select 1 from Topic where SystemName = 'HomePageText')
begin
	update Topic set Body=N'<div class="custom-product-details">  <h2>Custom Promotional Products, Gifts &amp; Items - Buy Wholesale and Save!</h2>  <p>Chances are that you have received business promotional items or corporate gifts at some in time past. and you probaby already know them by one of their many nicknames-swag. giveaways,promos logo gift. and so on . These promotional items-- such as <a>personalized pens</a>, <a>coffee mugs</a>, <a>T-shirt</a>, <a>tote bags</a>,<a>hand fans</a> and more - are imprinted with your logo or tagline and keep your brand top of mind with every use by your customer.</p>  <p>Business promotional items such as <a>keychains</a>, <a>notebooks</a>,<a>plastic bage</a>, and more are generally used to commemorate and advertise company events, build brand awareness at conventions and trade shows, and strengthen business relationships during peak or slow times of the year Frome... <a>read more</a></p>  </div>' where SystemName = 'HomePageText'
end
else
begin
	insert into Topic(SystemName,IncludeInSitemap,IncludeInTopMenu,IncludeInFooterColumn1,IncludeInFooterColumn2,IncludeInFooterColumn3,DisplayOrder,AccessibleWhenStoreClosed,IsPasswordProtected,Password,Title,Body,Published,TopicTemplateId,MetaKeywords,MetaDescription,MetaTitle,SubjectToAcl,LimitedToStores)
	values('HomePageText',0,0,0,0,0,1,0,0,NULL,NULL,N'<div class="custom-product-details">  <h2>Custom Promotional Products, Gifts &amp; Items - Buy Wholesale and Save!</h2>  <p>Chances are that you have received business promotional items or corporate gifts at some in time past. and you probaby already know them by one of their many nicknames-swag. giveaways,promos logo gift. and so on . These promotional items-- such as <a>personalized pens</a>, <a>coffee mugs</a>, <a>T-shirt</a>, <a>tote bags</a>,<a>hand fans</a> and more - are imprinted with your logo or tagline and keep your brand top of mind with every use by your customer.</p>  <p>Business promotional items such as <a>keychains</a>, <a>notebooks</a>,<a>plastic bage</a>, and more are generally used to commemorate and advertise company events, build brand awareness at conventions and trade shows, and strengthen business relationships during peak or slow times of the year Frome... <a>read more</a></p>  </div>',1,1,NULL,NULL,NULL,0,0)
end
Go
if exists(select 1 from Topic where SystemName = 'HomePageWhyUs')
begin
	update Topic set Body=N'<div class="Product-Samples-section">  <ul>  <li>  <div class="Product-Samples-title">Free Graphic Design &amp; Proofs</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/Free-graphic.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  <li>  <div class="Product-Samples-title">Guaranteed on Time Delivery</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/time-delivery.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  <li>  <div class="Product-Samples-title">Product Samples</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/product-samples.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  </ul>  </div>' where SystemName = 'HomePageWhyUs'
end
else
begin
	insert into Topic(SystemName,IncludeInSitemap,IncludeInTopMenu,IncludeInFooterColumn1,IncludeInFooterColumn2,IncludeInFooterColumn3,DisplayOrder,AccessibleWhenStoreClosed,IsPasswordProtected,Password,Title,Body,Published,TopicTemplateId,MetaKeywords,MetaDescription,MetaTitle,SubjectToAcl,LimitedToStores)
	values('HomePageWhyUs',0,0,0,0,0,1,0,0,NULL,NULL,N'<div class="Product-Samples-section">  <ul>  <li>  <div class="Product-Samples-title">Free Graphic Design &amp; Proofs</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/Free-graphic.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  <li>  <div class="Product-Samples-title">Guaranteed on Time Delivery</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/time-delivery.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  <li>  <div class="Product-Samples-title">Product Samples</div>  <div class="Product-Samples"><img src="/Content/Images/uploaded/product-samples.jpg" alt="" /></div>  <div class="Product-description">We offer blah blah and blah along with more blah...</div>  </li>  </ul>  </div>',1,1,NULL,NULL,NULL,0,0)
end
